version: '3.8'

services:
  service1:
    build:
      context: ./service1
    ports:
      - "5001:5000"
  service2:
    build:
      context: ./service2
    ports:
      - "5002:5000"

volumes:
    service1_data:
      driver: local
    service2_data:
      driver: local
networks:
  default:
    driver: bridge
